import "./globals.css";
import { Inter } from "next/font/google";

const roboto = Inter({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-neutral-50">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
