export const data = {
  frontend: {
    react: {
      ui: ["vanilla tailwind", "bootstrap", "material ui", "Radix UI"],
      stateManagement: ["redux", "context api", "mobx", "zustand"],
      testing: ["jest", "react testing library", "cypress"],
      routing: ["react router", "reach router", "next.js"],
      styling: ["css", "sass", "styled components", "emotion", "styled jsx"],
      fetching: ["axios", "fetch", "graphql"],
      animation: ["framer motion", "react spring", "react transition group"],
      forms: ["formik", "react hook form", "final form", "react form"],
      charts: ["recharts", "chart.js", "react-vis", "react-chartjs-2"],
      maps: ["react-map-gl", "google-map-react", "react-leaflet"],
      tables: ["react-table", "react-data-table", "ag-grid", "mui-datatables"],
      hosting: [
        "netlify",
        "vercel",
        "github pages",
        "firebase",
        "heroku",
        "aws",
        "digital ocean",
        "linode",
        "vultr",
        "azure",
        "google cloud",
      ],
    },
    vue: {
      ui: ["vanilla tailwind", "bootstrap", "material ui", "Radix UI"],
      stateManagement: ["vuex", "pinia", "vuestorefront"],
      testing: ["jest", "vue testing library", "cypress"],
      routing: ["vue router", "nuxt.js"],
      styling: ["css", "sass", "styled components", "emotion", "styled jsx"],
      fetching: ["axios", "fetch", "graphql"],
      animation: ["framer motion", "vue transition group"],
      forms: ["formik", "react hook form", "final form", "react form"],
      charts: ["recharts", "chart.js", "react-vis", "react-chartjs-2"],
    },
    angular: {
      ui: ["vanilla tailwind", "bootstrap", "material ui", "Radix UI"],
      stateManagement: ["ngrx", "akita", "ngxs"],
      testing: ["jest", "angular testing library", "cypress"],
      routing: ["angular router", "next.js"],
      styling: ["css", "sass", "styled components", "emotion", "styled jsx"],
    },
    svelte: {
      ui: ["vanilla tailwind", "bootstrap", "material ui", "Radix UI"],
      stateManagement: ["svelte store", "svelte zustand"],
      testing: ["jest", "svelte testing library", "cypress"],
      routing: ["svelte router", "sapper"],
    },
  },
  backend: {
    nodejs: {
      framework: [
        "express",
        "fastify",
        "nest.js",
        "hapi",
        "koa",
        "sails.js",
        "loopback",
        "adonis.js",
        "meteor.js",
        "restify",
        "total.js",
        "feathers.js",
        "actionhero.js",
        "moleculer",
        "seneca",
        "micro",
        "moleculer",
        "seneca",
        "micro",
      ],
      database: [
        "mongodb",
        "mysql",
        "postgresql",
        "redis",
        "elasticsearch",
        "cassandra",
        "neo4j",
        "couchdb",
        "rethinkdb",
        "firebase",
        "dynamodb",
        "sqlite",
        "mariadb",
        "arangodb",
        "influxdb",
        "orientdb",
        "teradata",
        "hbase",
        "couchbase",
        "realm",
        "fauna",
        "faunadb",
        "fauna db",
        "fauna cloud",
        "fauna labs",
        "fauna labs db",
        "fauna labs cloud",
        "fauna labs database",
        "fauna labs cloud database",
      ],
    },
    deno: {
      framework: [
        "oak",
        "abc",
        "deno-drash",
        "deno-express",
        "deno-opine",
        "deno-saur",
        "deno-servest",
        "deno-std",
        "deno-tinyhttp",
      ],
    },
  },
  fullstack: {
    nextjs: {
      database: [
        "mongodb",
        "mysql",
        "postgresql",
        "redis",
        "elasticsearch",
        "cassandra",
        "neo4j",
        "couchdb",
        "rethinkdb",
        "firebase",
        "dynamodb",
        "sqlite",
        "mariadb",
        "arangodb",
        "influxdb",
        "orientdb",
        "teradata",
        "hbase",
        "couchbase",
        "realm",
        "fauna",
        "faunadb",
        "fauna db",
        "fauna cloud",
        "fauna labs",
        "fauna labs db",
        "fauna labs cloud",
        "fauna labs database",
        "fauna labs cloud database",
      ],
      hosting: [
        "netlify",
        "vercel",
        "github pages",
        "firebase",
        "heroku",
        "aws",
        "digital ocean",
        "linode",
        "vultr",
        "azure",
        "google cloud",
      ],
    },
    nuxtjs: {
      database: [
        "mongodb",
        "mysql",
        "postgresql",
        "redis",
        "elasticsearch",
        "cassandra",
        "neo4j",
        "couchdb",
        "rethinkdb",
        "firebase",
        "dynamodb",
        "sqlite",
        "mariadb",
        "arangodb",
        "influxdb",
        "orientdb",
        "teradata",
        "hbase",
        "couchbase",
        "realm",
        "fauna",
        "faunadb",
        "fauna db",
        "fauna cloud",
        "fauna labs",
        "fauna labs db",
        "fauna labs cloud",
        "fauna labs database",
        "fauna labs cloud database",
      ],
      hosting: [
        "netlify",
        "vercel",
        "github pages",
        "firebase",
        "heroku",
        "aws",
        "digital ocean",
        "linode",
        "vultr",
        "azure",
        "google cloud",
      ],
    },
  },
};
